server:
  port: 8080
spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: ${sustechcourse.cloud.nacos.server-addr}
    gateway:
      routes:
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/email/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/captcha/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns:
              - "http://localhost:9527"
              - "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true
sustechcourse:
  jwt:
    location: classpath:jwt.jks
    alias: sustech-course
    password: sustech-course-123456
    tokenTTL: 30m
  auth:
    excludePaths:
      - /captcha/**
      - /email/**
      - /user/**
      - /admin/**
      - /hi