server:
  port: 8080
spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: ${sustechcourse.cloud.nacos.server-addr}
    gateway:
      routes:
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/email/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/captcha/**
sustechcourse:
  jwt:
    location: classpath:jwt.jks
    alias: sustech-course
    password: sustech-course-123456
    tokenTTL: 30m
  auth:
    excludePaths:
      - /captcha/**
      - /email/**
      - /user/**
      - /items/**
      - /hi