sustechcourse:
  database:
    host: 192.168.101.135
    database: sc-interaction
    password: mysql
  cloud:
    nacos:
      server-addr: 192.168.101.135:8848
  redis:
    host: 192.168.101.135
    port: 6379
    database: 0
    #password: redis
